/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ergonomicquizz.Quizz;

import ergonomicquizz.Init;
import static ergonomicquizz.Quizz.Ux_frame.username;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author yamada
 */
public class AgrupamentoLoc_frame extends javax.swing.JFrame {

    static String username;
    
    Date date = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    String data = formatador.format(date);
    
    /**
     * Creates new form AgrupamentoLoc_frame
     * @param username
     */
    public AgrupamentoLoc_frame(String username) {
        AgrupamentoLoc_frame.username = username;
        initComponents();
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    public void close() {
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
    
    public ArrayList<Integer> verificaVazio(ArrayList<String> button) {
        ArrayList<Integer>resp = new ArrayList<>();
        for (int i = 1; i <= button.size(); i++) {
            if (button.get(i-1) == null) {
                resp.add(i);
            } else if(button.get(i-1).equals("")) {
                resp.add(i);
            }
        }
        return resp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextArea4 = new javax.swing.JTextArea();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jTextArea5 = new javax.swing.JTextArea();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jTextArea6 = new javax.swing.JTextArea();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabelMessage3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setAlignmentX(0.0F);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1. O espaço de apresentação está diagramado em pequenas zonas funcionais? ");

        jRadioButton1.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Péssimo");

        jRadioButton2.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Ruim");

        jRadioButton3.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Bom");

        jRadioButton4.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Razoável");

        jRadioButton5.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Excelente");

        jLabel2.setBackground(new java.awt.Color(44, 62, 80));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2. A disposição dos objetos de interação de uma caixa de dialogo segue uma ordem lógica? ");

        jLabel3.setBackground(new java.awt.Color(44, 62, 80));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("3. Nos agrupamentos de dados, os itens estão organizados espacialmente segundo um critério lógico? ");

        jRadioButton11.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("Péssimo");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("Ruim");

        jRadioButton13.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton13);
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("Razoável");

        jRadioButton14.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton14);
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("Bom");

        jRadioButton15.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton15);
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("Excelente");

        jLabel4.setBackground(new java.awt.Color(44, 62, 80));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("4. Os códigos das teclas aceleradoras de opções de menu estão localizados à direita do nome da opção? ");

        jRadioButton16.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("Sim");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jRadioButton17.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton17);
        jRadioButton17.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("Não");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(37, 167, 240));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(44, 62, 80));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("5. Nas listas de seleção, as opções estão organizadas segundo alguma ordem lógica? ");

        jLabel7.setBackground(new java.awt.Color(44, 62, 80));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("6. Os paineis de menus são formados a partir de um critério lógico de agrupamento de opções? ");

        jLabel8.setBackground(new java.awt.Color(44, 62, 80));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("7. Dentro de um painel de menu, as opções mutuamente exclusivas ou interdependentes estão agrupadas e separadas das demais? ");

        jLabel9.setBackground(new java.awt.Color(44, 62, 80));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("8. As opções dentro de um painel de menu estão ordenadas segundo algum critério lógico? ");

        jLabel10.setBackground(new java.awt.Color(44, 62, 80));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("9. A definição da opção de menu selecionada por default segue algum critério? ");

        jLabel11.setBackground(new java.awt.Color(44, 62, 80));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("10. Os grupos de botões de comando estão dispostos em coluna e à direita, ou em linha e abaixo dos objetos aos quais estão associados? ");

        jTextArea3.setLineWrap(true);
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("11. O botão de comando selecionado por default está na posição mais alta, se os botões estão dispostos verticalmente, ou na mais à esquerda, se os botões estão dispostos horizontalmente? ");

        jTextArea4.setLineWrap(true);
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);

        jRadioButton6.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Péssimo");

        jRadioButton7.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Ruim");

        jRadioButton8.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Bom");

        jRadioButton9.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Razoável");

        jRadioButton10.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton10);
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Excelente");

        jRadioButton21.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton21);
        jRadioButton21.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton21.setText("Péssimo");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton22);
        jRadioButton22.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton22.setText("Ruim");

        jRadioButton45.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton45);
        jRadioButton45.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton45.setText("Razoável");

        jRadioButton46.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton46);
        jRadioButton46.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton46.setText("Bom");

        jRadioButton47.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton47);
        jRadioButton47.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton47.setText("Excelente");

        jRadioButton48.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton48);
        jRadioButton48.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton48.setText("Péssimo");
        jRadioButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton48ActionPerformed(evt);
            }
        });

        jRadioButton49.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton49);
        jRadioButton49.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton49.setText("Ruim");

        jRadioButton50.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton50);
        jRadioButton50.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton50.setText("Razoável");

        jRadioButton51.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton51);
        jRadioButton51.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton51.setText("Bom");

        jRadioButton52.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton52);
        jRadioButton52.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton52.setText("Excelente");

        jTextArea3.setLineWrap(true);
        jTextArea3.setWrapStyleWord(true);
        jTextArea5.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea5.setColumns(20);
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);

        jRadioButton53.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton53);
        jRadioButton53.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton53.setText("Péssimo");
        jRadioButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton53ActionPerformed(evt);
            }
        });

        jRadioButton54.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton54);
        jRadioButton54.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton54.setText("Ruim");

        jRadioButton55.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton55);
        jRadioButton55.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton55.setText("Razoável");

        jRadioButton56.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton56);
        jRadioButton56.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton56.setText("Bom");

        jRadioButton57.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton57);
        jRadioButton57.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton57.setText("Excelente");

        jTextArea3.setLineWrap(true);
        jTextArea3.setWrapStyleWord(true);
        jTextArea6.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea6.setColumns(20);
        jTextArea6.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea6.setRows(5);

        jRadioButton18.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("Não Aplicável");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jRadioButton19.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton19);
        jRadioButton19.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("Não Aplicável");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jRadioButton20.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton20);
        jRadioButton20.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("Não Aplicável");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton23.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton23);
        jRadioButton23.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton23.setText("Não Aplicável");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton58.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton58);
        jRadioButton58.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton58.setText("Não Aplicável");

        jRadioButton59.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton59);
        jRadioButton59.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton59.setText("Não Aplicável");

        jRadioButton60.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton60);
        jRadioButton60.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton60.setText("Não Aplicável");

        jPanel5.setBackground(new java.awt.Color(248, 148, 6));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Questionário de Agrupamento por Localização");

        jLabelMessage3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addGap(50, 50, 50)
                .addComponent(jLabelMessage3)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMessage3))
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(248, 32, 29));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton16)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton23))
                            .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton11)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton13)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton14)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton20))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton18))
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextArea6, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton53)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton54)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton55)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton56)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton60))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton48)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton49)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton50)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton51)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton59))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton21)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton22)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton45)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton46)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton58))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton9)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton19))
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton18))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton19))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton20))
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton23))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton45)
                    .addComponent(jRadioButton46)
                    .addComponent(jRadioButton47)
                    .addComponent(jRadioButton58))
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton48)
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton50)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton59))
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54)
                    .addComponent(jRadioButton55)
                    .addComponent(jRadioButton56)
                    .addComponent(jRadioButton57)
                    .addComponent(jRadioButton60))
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addComponent(jTextArea6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextArea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        buttonGroup6.clearSelection();
        buttonGroup7.clearSelection();
        jTextArea3.setText("");
        jTextArea4.setText("");
        jTextArea5.setText("");
        jTextArea6.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton53ActionPerformed

    private void jRadioButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton48ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String resp1 = getSelectedButtonText(buttonGroup1);
        String resp2 = getSelectedButtonText(buttonGroup2);
        String resp3 = getSelectedButtonText(buttonGroup3);
        String resp4 = getSelectedButtonText(buttonGroup4);
        String resp5 = getSelectedButtonText(buttonGroup5);
        String resp6 = getSelectedButtonText(buttonGroup6);
        String resp7 = jTextArea3.getText();
        String resp8 = getSelectedButtonText(buttonGroup7);
        String resp9 = jTextArea6.getText();
        String resp10 = jTextArea5.getText();
        String resp11 =  jTextArea4.getText();

        ArrayList<String> button = new ArrayList<>();
        button.add(resp1);
        button.add(resp2);
        button.add(resp3);
        button.add(resp4);
        button.add(resp5);
        button.add(resp6);
        button.add(resp7);
        button.add(resp8);
        button.add(resp9);
        button.add(resp10);
        button.add(resp11);

        ArrayList<Integer> questoesVazias = verificaVazio(button);
        if (questoesVazias.size() > 0) {
            String resp = null;
            if (questoesVazias.size() == 1) {
                resp = "A questão ";
            } else {
                resp = "As questões ";
            }
            for (int i = 0; i < questoesVazias.size(); i++) {
                // Se so tem 1 elemento
                if (questoesVazias.size() == 1) {
                    resp = resp + questoesVazias.get(i) + " não foi respondida.";
                } else{
                    // Se for penultima iteracao
                    if(i == questoesVazias.size()-2) {
                        resp = resp + questoesVazias.get(i) + " e ";
                        // Caso contrario
                    }else if (i == questoesVazias.size()-1){
                        resp = resp + questoesVazias.get(i) + " não foram respondidas.";
                    }else {
                        resp = resp + questoesVazias.get(i) + ", ";
                    }
                }
            }
            JOptionPane.showMessageDialog(null, resp);
            return;
        }

        BufferedWriter buffWrite = null;

        try {
            buffWrite = new BufferedWriter(new FileWriter("/home/yamada/Área de Trabalho/agrupamentoLoc_"+username+".txt"));
            buffWrite.append("Nome: "+ username +"\n");
            buffWrite.append("Data: "+ data + "\n\n");
            buffWrite.append(jLabel1.getText() + "\n");
            buffWrite.append("Resposta: "+ resp1 + "\n\n");
            buffWrite.append(jLabel2.getText() + "\n");
            buffWrite.append("Resposta: "+ resp2 + "\n\n");
            buffWrite.append(jLabel3.getText() + "\n");
            buffWrite.append("Resposta: "+ resp3 + "\n\n");
            buffWrite.append(jLabel4.getText() + "\n");
            buffWrite.append("Resposta: "+ resp4 + "\n\n");
            buffWrite.append(jLabel5.getText() + "\n");
            buffWrite.append("Resposta: "+ resp5 + "\n\n");
            buffWrite.append(jLabel7.getText() + "\n");
            buffWrite.append("Resposta: "+ resp6 + "\n\n");
            buffWrite.append(jLabel8.getText() + "\n");
            buffWrite.append("Resposta: "+ resp7 + "\n\n");
            buffWrite.append(jLabel9.getText() + "\n");
            buffWrite.append("Resposta: "+ resp8 + "\n\n");
            buffWrite.append(jLabel10.getText() + "\n");
            buffWrite.append("Resposta: "+ resp9 + "\n\n");
            buffWrite.append(jLabel11.getText() + "\n");
            buffWrite.append("Resposta: "+ resp10 + "\n\n");
            buffWrite.append(jLabel12.getText() + "\n");
            buffWrite.append("Resposta: "+ resp11 + "\n");
            buffWrite.close();

            String query = "insert into quizz.AgrupamentoLoc (username, data, p1, p2, p3, p4, p5, p6, p7, p8, p9 ,p10, p11)"+"values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizz", "root", " ")) {
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, username);
                pst.setString(2, data);

                pst.setString(3, resp1);
                pst.setString(4, resp2);
                pst.setString(5, resp3);
                pst.setString(6, resp4);
                pst.setString(7, resp5);
                pst.setString(8, resp6);
                pst.setString(9, resp7);
                pst.setString(10, resp8);
                pst.setString(11, resp9);
                pst.setString(12, resp10);
                pst.setString(13, resp11);

                pst.executeUpdate();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Prestreza_frame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Prestreza_frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Pronto!");
        this.dispose();
        Init i = new Init(username);
        i.setVisible(true);
        i.setTitle("Bem-Vindo(a)" + username +"!");
        i.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgrupamentoLoc_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgrupamentoLoc_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgrupamentoLoc_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgrupamentoLoc_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgrupamentoLoc_frame(username).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMessage3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}
