/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ergonomicquizz.Quizz;

import ergonomicquizz.Init;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.util.Date;
/**
 *
 * @author yamada
 */
public class Concisao_frame extends javax.swing.JFrame {
    
    static String username;
    
    Date date = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    String data = formatador.format(date);

    /**
     * Creates new form Concisao
     * @param username
     */
    public Concisao_frame(String username) {
        Concisao_frame.username = username;
        initComponents();
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
       for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
           AbstractButton button = buttons.nextElement();

           if (button.isSelected()) {
               return button.getText();
           }
       }

       return null;
    }
    
    public void close() {
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
     public ArrayList<Integer> verificaVazio(ArrayList<String> button) {
        ArrayList<Integer>resp = new ArrayList<>();
        for (int i = 1; i <= button.size(); i++) {
            if (button.get(i-1) == null) {
                resp.add(i);
            } else if(button.get(i-1).equals("")) {
                resp.add(i);
            }
        }
        return resp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jRadioButton61 = new javax.swing.JRadioButton();
        jRadioButton62 = new javax.swing.JRadioButton();
        jTextArea2 = new javax.swing.JTextArea();
        jRadioButton68 = new javax.swing.JRadioButton();
        jRadioButton69 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jRadioButton72 = new javax.swing.JRadioButton();
        jRadioButton78 = new javax.swing.JRadioButton();
        jRadioButton79 = new javax.swing.JRadioButton();
        jTextArea4 = new javax.swing.JTextArea();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton80 = new javax.swing.JRadioButton();
        jRadioButton73 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1. O sistema oferece valores defaults para acelerar a entrada de dados?");

        jRadioButton1.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Sim");

        jRadioButton2.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Não");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2.  A identificação alfanumérica das janelas é curta o suficiente para ser relembrada facilmente? ");

        jRadioButton6.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Péssimo");

        jRadioButton7.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Ruim");

        jRadioButton8.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Razoável");

        jRadioButton9.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Bom");

        jRadioButton10.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton10);
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Excelente");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("3. Os nomes das opções de menu são concisos?");

        jRadioButton11.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("1");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("2");

        jRadioButton13.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton13);
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("3");

        jRadioButton14.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton14);
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("4");

        jRadioButton15.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton15);
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("5");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("4. Os ícones são econômicos sob o ponto de vista do espaço nas telas?");

        jButton1.setBackground(new java.awt.Color(37, 167, 240));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("5. As denominações são breves?");

        jRadioButton29.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton29);
        jRadioButton29.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setText("Não");

        jRadioButton30.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton30);
        jRadioButton30.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setText("Sim");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("6. As abreviaturas são curtas? ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("7. Os códigos arbitrários que o usuário deve memorizar são sempre menores do que 4 ou 5 caracteres?");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("8. Os rótulos são concisos?");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("9. Os códigos alfanuméricos não significativos para o usuário e que devem ser entrados no sistema são menores do que 7 caracteres?");

        jRadioButton38.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup9.add(jRadioButton38);
        jRadioButton38.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton38.setText("Não");
        jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton38ActionPerformed(evt);
            }
        });

        jRadioButton39.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup9.add(jRadioButton39);
        jRadioButton39.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton39.setText("Sim");
        jRadioButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton39ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("11. Na entrada de dados numéricos, o usuário é liberado do preenchimento do ponto decimal desnecessário?");

        jRadioButton43.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup10.add(jRadioButton43);
        jRadioButton43.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton43.setText("Não");

        jRadioButton44.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup10.add(jRadioButton44);
        jRadioButton44.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton44.setText("Sim");
        jRadioButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton44ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("10. Na entrada de dados alfanuméricos, o sistema considera as letras maiúsculas e minúsculas como equivalentes? ");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("12. Na entrada de dados numéricos, o usuário é liberado do preenchimento do zeros fracionários desnecessários?");

        jRadioButton51.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton51);
        jRadioButton51.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton51.setText("6");
        jRadioButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton51ActionPerformed(evt);
            }
        });

        jRadioButton52.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton52);
        jRadioButton52.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton52.setText("7");

        jRadioButton53.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton53);
        jRadioButton53.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton53.setText("8");

        jRadioButton54.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton54);
        jRadioButton54.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton54.setText("9");

        jRadioButton55.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton55);
        jRadioButton55.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton55.setText("10");

        jRadioButton56.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton56);
        jRadioButton56.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton56.setText("Péssimo");

        jRadioButton57.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton57);
        jRadioButton57.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton57.setText("Ruim");

        jRadioButton58.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton58);
        jRadioButton58.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton58.setText("Razoável");

        jRadioButton59.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton59);
        jRadioButton59.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton59.setText("Bom");

        jRadioButton60.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton60);
        jRadioButton60.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton60.setText("Excelente");

        jRadioButton61.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton61);
        jRadioButton61.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton61.setText("Sim");
        jRadioButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton61ActionPerformed(evt);
            }
        });

        jRadioButton62.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton62);
        jRadioButton62.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton62.setText("Não");

        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);

        jRadioButton68.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup8.add(jRadioButton68);
        jRadioButton68.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton68.setText("Péssimo");

        jRadioButton69.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup8.add(jRadioButton69);
        jRadioButton69.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton69.setText("Ruim");

        jRadioButton70.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup8.add(jRadioButton70);
        jRadioButton70.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton70.setText("Razoável");

        jRadioButton71.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup8.add(jRadioButton71);
        jRadioButton71.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton71.setText("Bom");

        jRadioButton72.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup8.add(jRadioButton72);
        jRadioButton72.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton72.setText("Excelente");

        jRadioButton78.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton78);
        jRadioButton78.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton78.setText("Sim");
        jRadioButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton78ActionPerformed(evt);
            }
        });

        jRadioButton79.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton79);
        jRadioButton79.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton79.setText("Não");
        jRadioButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton79ActionPerformed(evt);
            }
        });

        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea4.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);

        jRadioButton3.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Não Aplicável");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton16.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton16);
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("Não Aplicável");

        jRadioButton63.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton63);
        jRadioButton63.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton63.setText("Não Aplicável");

        jRadioButton64.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton64);
        jRadioButton64.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton64.setText("Não Aplicável");

        jRadioButton31.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton31);
        jRadioButton31.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setText("Não Aplicável");

        jRadioButton65.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton65);
        jRadioButton65.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton65.setText("Aplicável");

        jRadioButton80.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton80);
        jRadioButton80.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton80.setText("Não Aplicável");
        jRadioButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton80ActionPerformed(evt);
            }
        });

        jRadioButton73.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup8.add(jRadioButton73);
        jRadioButton73.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton73.setText("Não Aplicável");

        jRadioButton40.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup9.add(jRadioButton40);
        jRadioButton40.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton40.setText("Não Aplicável");
        jRadioButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton40ActionPerformed(evt);
            }
        });

        jRadioButton45.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup10.add(jRadioButton45);
        jRadioButton45.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton45.setText("Não Aplicável");

        jPanel6.setBackground(new java.awt.Color(248, 148, 6));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Questionário de Concisão");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addContainerGap(768, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(248, 32, 29));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton11)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton13)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton14)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton15)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton51)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton52)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton53)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton54)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton64))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton9)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3))
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton30)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton29)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton31))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton39)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton38)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton40))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton44)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton43)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton45))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton56)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton57)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton58)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton59)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton61)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton62)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton65))
                            .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton68)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton69)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton70)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton71)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton72)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton73))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton78)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton79)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton80))))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButton2)
                        .addGap(124, 124, 124)
                        .addComponent(jButton1)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton16))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54)
                    .addComponent(jRadioButton55)
                    .addComponent(jRadioButton64))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton56)
                    .addComponent(jRadioButton57)
                    .addComponent(jRadioButton58)
                    .addComponent(jRadioButton59)
                    .addComponent(jRadioButton60)
                    .addComponent(jRadioButton63))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton31))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton61)
                    .addComponent(jRadioButton62)
                    .addComponent(jRadioButton65))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton78)
                    .addComponent(jRadioButton79)
                    .addComponent(jRadioButton80))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton68)
                    .addComponent(jRadioButton69)
                    .addComponent(jRadioButton70)
                    .addComponent(jRadioButton71)
                    .addComponent(jRadioButton72)
                    .addComponent(jRadioButton73))
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton40))
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton44)
                    .addComponent(jRadioButton43)
                    .addComponent(jRadioButton45))
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton79ActionPerformed

    private void jRadioButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton78ActionPerformed

    private void jRadioButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton61ActionPerformed

    private void jRadioButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton51ActionPerformed

    private void jRadioButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton44ActionPerformed

    private void jRadioButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton39ActionPerformed

    private void jRadioButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton38ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String resp1 = getSelectedButtonText(buttonGroup1);
        String resp2 = getSelectedButtonText(buttonGroup2);
        String resp3 = getSelectedButtonText(buttonGroup3);
        String resp4 = getSelectedButtonText(buttonGroup4);
        String resp5 = getSelectedButtonText(buttonGroup5);
        String resp6 = getSelectedButtonText(buttonGroup6);
        String resp7 = getSelectedButtonText(buttonGroup7);
        String resp8 = getSelectedButtonText(buttonGroup8);
        String resp9 = getSelectedButtonText(buttonGroup9);
        String resp10 = getSelectedButtonText(buttonGroup10);
        String resp11 = jTextArea2.getText();
        String resp12 = jTextArea4.getText();
        
        ArrayList<String> button = new ArrayList<>();
        button.add(resp1);
        button.add(resp2);
        button.add(resp3);
        button.add(resp4);
        button.add(resp5);
        button.add(resp6);
        button.add(resp7);
        button.add(resp8);
        button.add(resp9);
        button.add(resp10);
        button.add(resp11);
        button.add(resp12);
        
        ArrayList<Integer> questoesVazias = verificaVazio(button);
        if (questoesVazias.size() > 0) {
            String resp = null;
            if (questoesVazias.size() == 1) {
                resp = "A questão ";
            } else {
                resp = "As questões ";
            }
            for (int i = 0; i < questoesVazias.size(); i++) {
                // Se so tem 1 elemento
                if (questoesVazias.size() == 1) {
                    resp = resp + questoesVazias.get(i) + " não foi respondida.";
                } else{
                    // Se for penultima iteracao
                    if(i == questoesVazias.size()-2) {    
                        resp = resp + questoesVazias.get(i) + " e ";
                    // Caso contrario
                    }else if (i == questoesVazias.size()-1){
                        resp = resp + questoesVazias.get(i) + " não foram respondidas.";
                    }else {
                        resp = resp + questoesVazias.get(i) + ", ";
                    }
                }
            }
            JOptionPane.showMessageDialog(null, resp);
            return;
        }

        BufferedWriter buffWrite = null;

       try {
            buffWrite = new BufferedWriter(new FileWriter("/home/yamada/Área de Trabalho/concisao_"+username+".txt"));
            buffWrite.append("Nome: " + username + "\n");
            buffWrite.append("Data: " + data + "\n\n");
            buffWrite.append(jLabel1.getText() + "\n");
            buffWrite.append("Resposta: "+ resp1 + "\n\n");
            buffWrite.append(jLabel2.getText() + "\n");
            buffWrite.append("Resposta: "+ resp2 + "\n\n");
            buffWrite.append(jLabel3.getText() + "\n");
            buffWrite.append("Resposta: "+ resp3 + "\n\n");
            buffWrite.append(jLabel4.getText() + "\n");
            buffWrite.append("Resposta: "+ resp4 + "\n\n");
            buffWrite.append(jLabel5.getText() + "\n");
            buffWrite.append("Resposta: "+ resp5 + "\n\n");
            buffWrite.append(jLabel6.getText() + "\n");
            buffWrite.append("Resposta: "+ resp6 + "\n\n");
            buffWrite.append(jLabel7.getText() + "\n");
            buffWrite.append("Resposta: "+ resp7 + "\n\n");
            buffWrite.append(jLabel8.getText() + "\n");
            buffWrite.append("Resposta: "+ resp8 + "\n\n");
            buffWrite.append(jLabel9.getText() + "\n");
            buffWrite.append("Resposta: "+ resp9 + "\n\n");
            buffWrite.append(jLabel10.getText() + "\n");
            buffWrite.append("Resposta: "+ resp10 + "\n\n");
            buffWrite.append(jLabel11.getText() + "\n");
            buffWrite.append("Resposta: "+ resp11 + "\n\n");
            buffWrite.append(jLabel12.getText() + "\n");
            buffWrite.append("Resposta: "+ resp12 + "\n");
            buffWrite.close();
            
            String query = "insert into quizz.Concisao (username, data, p1, p2, p3, p4, p5, p6, p7, p8, p9 ,p10, p11, p12)"+"values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizz", "root", " ")) {
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, username);
                pst.setString(2, data);
                
                pst.setString(3, resp1);
                pst.setString(4, resp2);
                pst.setString(5, resp3);
                pst.setString(6, resp4);
                pst.setString(7, resp5);
                pst.setString(8, resp6);
                pst.setString(9, resp7);
                pst.setString(10, resp8);
                pst.setString(11, resp9);
                pst.setString(12, resp10);
                pst.setString(13, resp11);
                pst.setString(14, resp12);
                
                pst.executeUpdate();
                con.close();
            }

        } catch (IOException ex) {
            Logger.getLogger(Prestreza_frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Feedback_frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Pronto!");
        this.dispose();
        Init i = new Init(username);
        i.setVisible(true);
        i.setTitle("Bem-Vindo(a)" + username +"!");
        i.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton80ActionPerformed

    private void jRadioButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton40ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection(); 
        buttonGroup6.clearSelection();
        buttonGroup7.clearSelection();
        buttonGroup8.clearSelection();
        buttonGroup9.clearSelection();
        buttonGroup10.clearSelection();
        jTextArea2.setText("");
        jTextArea4.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Concisao_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Concisao_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Concisao_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Concisao_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Concisao_frame(username).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton61;
    private javax.swing.JRadioButton jRadioButton62;
    private javax.swing.JRadioButton jRadioButton63;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton68;
    private javax.swing.JRadioButton jRadioButton69;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton72;
    private javax.swing.JRadioButton jRadioButton73;
    private javax.swing.JRadioButton jRadioButton78;
    private javax.swing.JRadioButton jRadioButton79;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton80;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
