/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ergonomicquizz.Quizz;

import ergonomicquizz.Init;
import static ergonomicquizz.Quizz.Ux_frame.username;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.util.Date;
/**
 *
 * @author yamada
 */
public class MensagemErro_frame extends javax.swing.JFrame {
    
    static String username;
    
    Date date = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    String data = formatador.format(date);

    /**
     * Creates new form MensagemErro_grame
     * @param username
     */
    public MensagemErro_frame(String username) {
        MensagemErro_frame.username = username;
        initComponents();
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
       for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
           AbstractButton button = buttons.nextElement();

           if (button.isSelected()) {
               return button.getText();
           }
       }

       return null;
    }

    public void close() {
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
    public ArrayList<Integer> verificaVazio(ArrayList<String> button) {
        ArrayList<Integer>resp = new ArrayList<>();
        for (int i = 1; i <= button.size(); i++) {
            if (button.get(i-1) == null) {
                resp.add(i);
            } else if(button.get(i-1).equals("")) {
                resp.add(i);
            }
        }
        return resp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jTextArea4 = new javax.swing.JTextArea();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jTextArea5 = new javax.swing.JTextArea();
        jRadioButton61 = new javax.swing.JRadioButton();
        jRadioButton62 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton66 = new javax.swing.JRadioButton();
        jRadioButton67 = new javax.swing.JRadioButton();
        jRadioButton68 = new javax.swing.JRadioButton();
        jRadioButton69 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1. As mensagens de erro ajudam a resolver o problema do usuário, fornecendo com precisão o local e a causa específica ou provável do erro, bem como as ações que o usuário poderia realizar para corrigí-l o?");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2. As mensagens de erro são neutras e polidas? ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("3. As frases das mensagens de erro são curtas e construídas a partir de palavras curtas, significativas e de uso comum? ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("4.  As mensagens de erro estão isentas de abreviaturas e/ou códigos gerados pelo sistema operacional? ");

        jButton1.setBackground(new java.awt.Color(37, 167, 240));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("5. O usuário pode escolher o nível de detalhe das mensagens de erro em função de seu nível de conhecimento? ");

        jRadioButton26.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton26);
        jRadioButton26.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setText("Excelente");

        jRadioButton27.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton27);
        jRadioButton27.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setText("Bom");

        jRadioButton28.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton28);
        jRadioButton28.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setText("Razoável");

        jRadioButton29.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton29);
        jRadioButton29.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setText("Ruim");

        jRadioButton30.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton30);
        jRadioButton30.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setText("Péssimo");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("6. A informação principal de uma mensagem de erro encontra-se logo no início da mensagem? ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("7. Quando necessário, as informações que o usuário deve memorizar encontram-se localizadas na parte final da mensagem de erro? ");

        jRadioButton34.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton34);
        jRadioButton34.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton34.setText("Não");

        jRadioButton35.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton35);
        jRadioButton35.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton35.setText("Sim");
        jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton35ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("8. Em situações normais as mensagens de erro são escritas em maiúsculo/minúsculo? ");

        jRadioButton3.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Não");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Sim");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("9. As mensagens de erro têm seu conteúdo modificado quando na repetição imediata do mesmo erro pelo mesmo usuário? ");

        jRadioButton38.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton38);
        jRadioButton38.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton38.setText("Não");

        jRadioButton39.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton39);
        jRadioButton39.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton39.setText("Sim");
        jRadioButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton39ActionPerformed(evt);
            }
        });

        jTextArea4.setLineWrap(true);
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);

        jRadioButton51.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton51);
        jRadioButton51.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton51.setText("1");
        jRadioButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton51ActionPerformed(evt);
            }
        });

        jRadioButton52.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton52);
        jRadioButton52.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton52.setText("2");

        jRadioButton53.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton53);
        jRadioButton53.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton53.setText("3");

        jRadioButton54.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton54);
        jRadioButton54.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton54.setText("4");

        jRadioButton55.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton55);
        jRadioButton55.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton55.setText("5");

        jRadioButton56.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton56);
        jRadioButton56.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton56.setText("10");

        jRadioButton57.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton57);
        jRadioButton57.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton57.setText("9");

        jRadioButton58.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton58);
        jRadioButton58.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton58.setText("8");

        jRadioButton59.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton59);
        jRadioButton59.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton59.setText("7");

        jRadioButton60.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton60);
        jRadioButton60.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton60.setText("6");
        jRadioButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton60ActionPerformed(evt);
            }
        });

        jTextArea5.setLineWrap(true);
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea5.setColumns(20);
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);

        jRadioButton61.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton61);
        jRadioButton61.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton61.setText("Excelente");

        jRadioButton62.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton62);
        jRadioButton62.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton62.setText("Bom");

        jRadioButton63.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton63);
        jRadioButton63.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton63.setText("Razoável");

        jRadioButton64.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton64);
        jRadioButton64.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton64.setText("Ruim");

        jRadioButton65.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton65);
        jRadioButton65.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton65.setText("Péssimo");
        jRadioButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton65ActionPerformed(evt);
            }
        });

        jRadioButton66.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton66);
        jRadioButton66.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton66.setText("Sim");
        jRadioButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton66ActionPerformed(evt);
            }
        });

        jRadioButton67.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton67);
        jRadioButton67.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton67.setText("Não");

        jRadioButton68.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton68);
        jRadioButton68.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton68.setText("Não Aplicável");

        jRadioButton69.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton69);
        jRadioButton69.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton69.setText("Não Aplicável");

        jRadioButton31.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton31);
        jRadioButton31.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setText("Não Aplicável");

        jRadioButton70.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup4.add(jRadioButton70);
        jRadioButton70.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton70.setText("Não Aplicável");

        jRadioButton36.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton36);
        jRadioButton36.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton36.setText("Não Aplicável");

        jRadioButton5.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup6.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Não Aplicável");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton40.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup7.add(jRadioButton40);
        jRadioButton40.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton40.setText("Não Aplicável");

        jPanel5.setBackground(new java.awt.Color(248, 148, 6));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Questionário de Mensagem de Erro");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addContainerGap(768, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(248, 32, 29));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton30)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton29)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton28)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton27)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton26)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton31))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton35)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton34)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton36))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton5))
                            .addComponent(jLabel9)
                            .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton51)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton52)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton53)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton54)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton55)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton60)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton59)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton58)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton57)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton56)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton68))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton65)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton64)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton63)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton62)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton61)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton69))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton66)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton67)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton70))
                            .addComponent(jTextArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton39)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton38)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton40)))
                                .addGap(99, 99, 99)
                                .addComponent(jButton1))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextArea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54)
                    .addComponent(jRadioButton55)
                    .addComponent(jRadioButton60)
                    .addComponent(jRadioButton59)
                    .addComponent(jRadioButton58)
                    .addComponent(jRadioButton57)
                    .addComponent(jRadioButton56)
                    .addComponent(jRadioButton68))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton65)
                    .addComponent(jRadioButton64)
                    .addComponent(jRadioButton63)
                    .addComponent(jRadioButton62)
                    .addComponent(jRadioButton61)
                    .addComponent(jRadioButton69))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton31))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton66)
                    .addComponent(jRadioButton67)
                    .addComponent(jRadioButton70))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton36))
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton5))
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton40))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        buttonGroup6.clearSelection();
        buttonGroup7.clearSelection();
        jTextArea4.setText("");
        jTextArea5.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton66ActionPerformed

    private void jRadioButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton65ActionPerformed

    private void jRadioButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton60ActionPerformed

    private void jRadioButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton51ActionPerformed

    private void jRadioButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton39ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton35ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String resp1 = jTextArea5.getText();
        String resp2 = getSelectedButtonText(buttonGroup1);
        String resp3 = jTextArea4.getText();
        String resp4 = getSelectedButtonText(buttonGroup2);
        String resp5 = getSelectedButtonText(buttonGroup3);
        String resp6 = getSelectedButtonText(buttonGroup4);
        String resp7 = getSelectedButtonText(buttonGroup5);
        String resp8 = getSelectedButtonText(buttonGroup6);
        String resp9 = getSelectedButtonText(buttonGroup7);

        ArrayList<String> button = new ArrayList<>();
        button.add(resp1);
        button.add(resp2);
        button.add(resp3);
        button.add(resp4);
        button.add(resp5);
        button.add(resp6);
        button.add(resp7);
        button.add(resp8);
        button.add(resp9);

        ArrayList<Integer> questoesVazias = verificaVazio(button);
        if (questoesVazias.size() > 0) {
            String resp = null;
            if (questoesVazias.size() == 1) {
                resp = "A questão ";
            } else {
                resp = "As questões ";
            }
            for (int i = 0; i < questoesVazias.size(); i++) {
                // Se so tem 1 elemento
                if (questoesVazias.size() == 1) {
                    resp = resp + questoesVazias.get(i) + " não foi respondida.";
                } else{
                    // Se for penultima iteracao
                    if(i == questoesVazias.size()-2) {
                        resp = resp + questoesVazias.get(i) + " e ";
                        // Caso contrario
                    }else if (i == questoesVazias.size()-1){
                        resp = resp + questoesVazias.get(i) + " não foram respondidas.";
                    }else {
                        resp = resp + questoesVazias.get(i) + ", ";
                    }
                }
            }
            JOptionPane.showMessageDialog(null, resp);
            return;
        }

        BufferedWriter buffWrite = null;

        try {
            buffWrite = new BufferedWriter(new FileWriter("/home/yamada/Área de Trabalho/msgErro_"+username+".txt"));
            buffWrite.append("Nome: " + username + "\n");
            buffWrite.append("Data: " + data + "\n\n");
            buffWrite.append(jLabel1.getText() + "\n");
            buffWrite.append("Resposta: "+ resp1 + "\n\n");
            buffWrite.append(jLabel2.getText() + "\n");
            buffWrite.append("Resposta: "+ resp2 + "\n\n");
            buffWrite.append(jLabel3.getText() + "\n");
            buffWrite.append("Resposta: "+ resp3 + "\n\n");
            buffWrite.append(jLabel4.getText() + "\n");
            buffWrite.append("Resposta: "+ resp4 + "\n\n");
            buffWrite.append(jLabel5.getText() + "\n");
            buffWrite.append("Resposta: "+ resp5 + "\n\n");
            buffWrite.append(jLabel6.getText() + "\n");
            buffWrite.append("Resposta: "+ resp6 + "\n\n");
            buffWrite.append(jLabel7.getText() + "\n");
            buffWrite.append("Resposta: "+ resp7 + "\n\n");
            buffWrite.append(jLabel8.getText() + "\n");
            buffWrite.append("Resposta: "+ resp8 + "\n\n");
            buffWrite.append(jLabel9.getText() + "\n");
            buffWrite.append("Resposta: "+ resp9 + "\n");
            buffWrite.close();

            String query = "insert into quizz.MensagemErro (username, data, p1, p2, p3, p4, p5, p6, p7, p8, p9)"+"values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizz", "root", "")) {
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, username);
                pst.setString(2, data);

                pst.setString(3, resp1);
                pst.setString(4, resp2);
                pst.setString(5, resp3);
                pst.setString(6, resp4);
                pst.setString(7, resp5);
                pst.setString(8, resp6);
                pst.setString(9, resp7);
                pst.setString(10, resp8);
                pst.setString(11, resp9);

                pst.executeUpdate();
                con.close();
            }

        } catch (IOException ex) {
            Logger.getLogger(Prestreza_frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Feedback_frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Pronto!");
        this.dispose();
        Init i = new Init(username);
        i.setVisible(true);
        i.setTitle("Bem-Vindo(a)" + username +"!");
        i.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensagemErro_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensagemErro_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensagemErro_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensagemErro_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MensagemErro_frame(username).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton61;
    private javax.swing.JRadioButton jRadioButton62;
    private javax.swing.JRadioButton jRadioButton63;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton66;
    private javax.swing.JRadioButton jRadioButton67;
    private javax.swing.JRadioButton jRadioButton68;
    private javax.swing.JRadioButton jRadioButton69;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
