/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ergonomicquizz.Quizz;

import ergonomicquizz.Init;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author yamada
 */
public class Ux_frame extends javax.swing.JFrame {

    static String username;

    Date date = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    String data = formatador.format(date);
    
    
    /**
     * Creates new form Ux_frame
     * @param username
     */
    public Ux_frame(String username) {
        this.username = username;
        initComponents();
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    public void close() {
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
    
        public ArrayList<Integer> verificaVazio(ArrayList<String> button) {
        ArrayList<Integer>resp = new ArrayList<>();
        for (int i = 1; i <= button.size(); i++) {
            if (button.get(i-1) == null) {
                resp.add(i);
            } else if(button.get(i-1).equals("")) {
                resp.add(i);
            }
        }
        return resp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jTextArea2 = new javax.swing.JTextArea();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabelMessage3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1. Caso se trate de um sistema de grande público, ele fornece formas variádas de apresentar as mesmas informações aos diferentes tipos de usuário?");

        jRadioButton23.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton23);
        jRadioButton23.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton23.setText("Péssimo");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton24.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton24);
        jRadioButton24.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton24.setText("Ruim");

        jRadioButton25.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton25);
        jRadioButton25.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton25.setText("Bom");

        jRadioButton26.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setText("Razoável");

        jRadioButton27.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton27);
        jRadioButton27.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setText("Excelente");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2. Os estilos de diálogo são compatíveis com as habilidades do usuário, permitindo ações passo-a-passo para iniciantes e a entrada de comandos mais complexos por usuários experimentados? ");

        jRadioButton28.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton28);
        jRadioButton28.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setText("Péssimo");

        jRadioButton29.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton29);
        jRadioButton29.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setText("Ruim");

        jRadioButton30.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton30);
        jRadioButton30.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setText("Razoável");

        jRadioButton31.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton31);
        jRadioButton31.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setText("Bom");

        jRadioButton32.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton32);
        jRadioButton32.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton32.setText("Excelente");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("3. O usuário pode se deslocar de uma parte da estrutura de menu para outra rapidamente? ");

        jRadioButton33.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton33);
        jRadioButton33.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton33.setText("1");
        jRadioButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton33ActionPerformed(evt);
            }
        });

        jRadioButton34.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton34);
        jRadioButton34.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton34.setText("2");

        jRadioButton35.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton35);
        jRadioButton35.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton35.setText("3");

        jRadioButton36.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton36);
        jRadioButton36.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton36.setText("4");

        jRadioButton37.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton37);
        jRadioButton37.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton37.setText("5");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("4. O sistema é capaz de reconhecer um conjunto de sinônimos para os termos básicos definidos na linguagem de comando, isto para se adaptar aos usuários novatos ou ocasionais? ");

        jButton1.setBackground(new java.awt.Color(37, 167, 240));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton43.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton43);
        jRadioButton43.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton43.setText("6");
        jRadioButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton43ActionPerformed(evt);
            }
        });

        jRadioButton44.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton44);
        jRadioButton44.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton44.setText("7");

        jRadioButton45.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton45);
        jRadioButton45.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton45.setText("8");

        jRadioButton46.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton46);
        jRadioButton46.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton46.setText("9");

        jRadioButton47.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton47);
        jRadioButton47.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton47.setText("10");

        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBackground(new java.awt.Color(108, 122, 137));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);

        jRadioButton48.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton48);
        jRadioButton48.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton48.setText("Péssimo");
        jRadioButton48.setToolTipText("");
        jRadioButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton48ActionPerformed(evt);
            }
        });

        jRadioButton49.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton49);
        jRadioButton49.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton49.setText("Ruim");
        jRadioButton49.setToolTipText("");

        jRadioButton50.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton50);
        jRadioButton50.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton50.setText("Razoável");
        jRadioButton50.setToolTipText("");

        jRadioButton51.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton51);
        jRadioButton51.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton51.setText("Bom");
        jRadioButton51.setToolTipText("");

        jRadioButton52.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton52);
        jRadioButton52.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton52.setText("Excelente");
        jRadioButton52.setToolTipText("");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("5. O usuário experiente pode efetuar a digitação de vários comandos antes de uma confirmação? ");

        jRadioButton53.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(jRadioButton53);
        jRadioButton53.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton53.setText("Não Aplicável");

        jRadioButton54.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup2.add(jRadioButton54);
        jRadioButton54.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton54.setText("Não Aplicável");

        jRadioButton55.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup3.add(jRadioButton55);
        jRadioButton55.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton55.setText("Não Aplicável");

        jRadioButton57.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup5.add(jRadioButton57);
        jRadioButton57.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton57.setText("Não Aplicável");
        jRadioButton57.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(248, 148, 6));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Questionário de UX");

        jLabelMessage3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addGap(50, 50, 50)
                .addComponent(jLabelMessage3)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMessage3))
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(248, 32, 29));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton33)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton34)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton35)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton36)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton37)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton43)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton44)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton45)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton46)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton47)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton55))
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton28)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton29)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton30)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton31)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton32)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton54))
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton23)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton24)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton26)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton25)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton27)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton53))
                            .addComponent(jLabel7)
                            .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton48)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton49)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton50)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton51)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton52)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton57))
                            .addComponent(jLabel13)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton2)
                        .addGap(119, 119, 119)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton53))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton31)
                    .addComponent(jRadioButton32)
                    .addComponent(jRadioButton54))
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton33)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton37)
                    .addComponent(jRadioButton43)
                    .addComponent(jRadioButton44)
                    .addComponent(jRadioButton45)
                    .addComponent(jRadioButton46)
                    .addComponent(jRadioButton47)
                    .addComponent(jRadioButton55))
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton48)
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton50)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton52)
                    .addComponent(jRadioButton57))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jRadioButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton48ActionPerformed

    private void jRadioButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton43ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String resp1 = getSelectedButtonText(buttonGroup1);
        String resp2 = getSelectedButtonText(buttonGroup2);
        String resp3 = getSelectedButtonText(buttonGroup3);
        String resp4 = jTextArea2.getText();
        String resp5 = getSelectedButtonText(buttonGroup5);

        ArrayList<String> button = new ArrayList<>();
        button.add(resp1);
        button.add(resp2);
        button.add(resp3);
        button.add(resp4);
        button.add(resp5);

        ArrayList<Integer> questoesVazias = verificaVazio(button);
        if (questoesVazias.size() > 0) {
            String resp = null;
            if (questoesVazias.size() == 1) {
                resp = "A questão ";
            } else {
                resp = "As questões ";
            }
            for (int i = 0; i < questoesVazias.size(); i++) {
                // Se so tem 1 elemento
                if (questoesVazias.size() == 1) {
                    resp = resp + questoesVazias.get(i) + " não foi respondida.";
                } else{
                    // Se for penultima iteracao
                    if(i == questoesVazias.size()-2) {
                        resp = resp + questoesVazias.get(i) + " e ";
                        // Caso contrario
                    }else if (i == questoesVazias.size()-1){
                        resp = resp + questoesVazias.get(i) + " não foram respondidas.";
                    }else {
                        resp = resp + questoesVazias.get(i) + ", ";
                    }
                }
            }
            JOptionPane.showMessageDialog(null, resp);
            return;
        }

        BufferedWriter buffWrite = null;

        try {
            buffWrite = new BufferedWriter(new FileWriter("/home/yamada/Área de Trabalho/ux_"+username+".txt"));
            buffWrite.append("Nome: " + username+ "\n");
            buffWrite.append("Data: " + data + "\n\n");
            buffWrite.append(jLabel7.getText() + "\n");
            buffWrite.append("Resposta: "+ resp1 + "\n\n");
            buffWrite.append(jLabel8.getText() + "\n");
            buffWrite.append("Resposta: "+ resp2 + "\n\n");
            buffWrite.append(jLabel9.getText() + "\n");
            buffWrite.append("Resposta: "+ resp3 + "\n\n");
            buffWrite.append(jLabel10.getText() + "\n");
            buffWrite.append("Resposta: "+ resp4 + "\n\n");
            buffWrite.append(jLabel13.getText() + "\n");
            buffWrite.append("Resposta: "+ resp5 + "\n");
            buffWrite.close();

            String query = "insert into quizz.UX (username, data, p1, p2, p3, p4, p5)"+"values(?, ?, ?, ?, ?, ?, ?)";
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizz", "root", " ")) {
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, username);
                pst.setString(2, data);

                pst.setString(3, resp1);
                pst.setString(4, resp2);
                pst.setString(5, resp3);
                pst.setString(6, resp4);
                pst.setString(7, resp5);

                pst.executeUpdate();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Ux_frame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (IOException ex) {
            Logger.getLogger(Prestreza_frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ux_frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Pronto!");
        this.dispose();
        Init i = new Init(username);
        i.setVisible(true);
        i.setTitle("Bem-Vindo(a)" + username +"!");
        i.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton33ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ux_frame(username).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMessage3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
