/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ergonomicquizz;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author yamada
 */
public class Ux_frame extends javax.swing.JFrame {

    static String pnome, unome, email;

    Date date = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    String data = formatador.format(date);
    
    
    /**
     * Creates new form Ux_frame
     * @param pnome
     * @param unome
     * @param email
     */
    public Ux_frame(String pnome, String unome, String email) {
        this.pnome = pnome;
        this.unome = unome;
        this.email = email;
        initComponents();
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    public void close() {
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jTextArea2 = new javax.swing.JTextArea();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("1. Caso se trate de um sistema de grande público, ele fornece formas variádas de apresentar as mesmas informações aos diferentes tipos de usuário?");

        buttonGroup1.add(jRadioButton23);
        jRadioButton23.setText("Péssimo");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton24);
        jRadioButton24.setText("Ruim");

        buttonGroup1.add(jRadioButton25);
        jRadioButton25.setText("Bom");

        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setText("Razoável");

        buttonGroup1.add(jRadioButton27);
        jRadioButton27.setText("Excelente");

        jLabel8.setText("2. \t\t\t\t\tOs estilos de diálogo são compatíveis com as habilidades do usuário, permitindo ações passo-a-passo para iniciantes e a entrada de comandos mais complexos por usuários experimentados? ");

        buttonGroup2.add(jRadioButton28);
        jRadioButton28.setText("Péssimo");

        buttonGroup2.add(jRadioButton29);
        jRadioButton29.setText("Ruim");

        buttonGroup2.add(jRadioButton30);
        jRadioButton30.setText("Razoável");

        buttonGroup2.add(jRadioButton31);
        jRadioButton31.setText("Bom");

        buttonGroup2.add(jRadioButton32);
        jRadioButton32.setText("Excelente");

        jLabel9.setText("3. O usuário pode se deslocar de uma parte da estrutura de menu para outra rapidamente? ");

        buttonGroup3.add(jRadioButton33);
        jRadioButton33.setText("1");
        jRadioButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton33ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton34);
        jRadioButton34.setText("2");

        buttonGroup3.add(jRadioButton35);
        jRadioButton35.setText("3");

        buttonGroup3.add(jRadioButton36);
        jRadioButton36.setText("4");

        buttonGroup3.add(jRadioButton37);
        jRadioButton37.setText("5");

        jLabel10.setText("4. \t\t\t\t\tO sistema é capaz de reconhecer um conjunto de sinônimos para os termos básicos definidos na linguagem de comando, isto para se adap tar aos usuários novatos ou ocasionais? ");

        buttonGroup4.add(jRadioButton38);
        jRadioButton38.setText("Péssimo");
        jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton38ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton39);
        jRadioButton39.setText("Ruim");

        buttonGroup4.add(jRadioButton40);
        jRadioButton40.setText("Razoável");

        buttonGroup4.add(jRadioButton41);
        jRadioButton41.setText("Bom");

        buttonGroup4.add(jRadioButton42);
        jRadioButton42.setText("Excelente");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("5. O usuário experiente pode efetuar a digitação de vários comandos antes de uma confirmação? ");

        buttonGroup3.add(jRadioButton43);
        jRadioButton43.setText("6");
        jRadioButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton43ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton44);
        jRadioButton44.setText("7");

        buttonGroup3.add(jRadioButton45);
        jRadioButton45.setText("8");

        buttonGroup3.add(jRadioButton46);
        jRadioButton46.setText("9");

        buttonGroup3.add(jRadioButton47);
        jRadioButton47.setText("10");

        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);

        buttonGroup5.add(jRadioButton48);
        jRadioButton48.setText("Péssimo");
        jRadioButton48.setToolTipText("");
        jRadioButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton48ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButton49);
        jRadioButton49.setText("Ruim");
        jRadioButton49.setToolTipText("");

        buttonGroup5.add(jRadioButton50);
        jRadioButton50.setText("Razoável");
        jRadioButton50.setToolTipText("");

        buttonGroup5.add(jRadioButton51);
        jRadioButton51.setText("Bom");
        jRadioButton51.setToolTipText("");

        buttonGroup5.add(jRadioButton52);
        jRadioButton52.setText("Excelente");
        jRadioButton52.setToolTipText("");

        jLabel13.setText("6. O usuário experiente pode efetuar a digitação de vários comandos antes de uma confirmação? ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton33)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton34)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton35)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton36)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton37)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton43)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton44)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton45)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton46)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton47))
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton28)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton29)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton30)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton31)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton32))
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton23)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton24)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton26)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton25)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton27))
                            .addComponent(jLabel7)
                            .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton38)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton39)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton40)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton41)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton42))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton48)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton49)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton50)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton51)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton52))
                            .addComponent(jLabel13)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton27))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton31)
                    .addComponent(jRadioButton32))
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton33)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton37)
                    .addComponent(jRadioButton43)
                    .addComponent(jRadioButton44)
                    .addComponent(jRadioButton45)
                    .addComponent(jRadioButton46)
                    .addComponent(jRadioButton47))
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton40)
                    .addComponent(jRadioButton41)
                    .addComponent(jRadioButton42))
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton48)
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton50)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton52))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton33ActionPerformed

    private void jRadioButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton38ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String resp1 = getSelectedButtonText(buttonGroup1);
        String resp2 = getSelectedButtonText(buttonGroup2);
        String resp3 = getSelectedButtonText(buttonGroup3);
        String resp4 = jTextArea2.getText();
        String resp5 = getSelectedButtonText(buttonGroup4);
        String resp6 = getSelectedButtonText(buttonGroup5);
        
        BufferedWriter buffWrite = null;
        
        try {
            buffWrite = new BufferedWriter(new FileWriter("/home/yamada/Área de Trabalho/ux_"+pnome+unome+".txt"));
            buffWrite.append("Nome: " + pnome + " " +unome + "\n");
            buffWrite.append("Email: " + email + "\n");
            buffWrite.append("Data: " + data + "\n\n");
            buffWrite.append(jLabel7.getText() + "\n");
            buffWrite.append("Resposta: "+ resp1 + "\n\n");
            buffWrite.append(jLabel8.getText() + "\n");
            buffWrite.append("Resposta: "+ resp2 + "\n\n");
            buffWrite.append(jLabel9.getText() + "\n");
            buffWrite.append("Resposta: "+ resp3 + "\n\n");
            buffWrite.append(jLabel10.getText() + "\n");
            buffWrite.append("Resposta: "+ resp4 + "\n\n");
            buffWrite.append(jLabel11.getText() + "\n");
            buffWrite.append("Resposta: "+ resp5 + "\n\n");
            buffWrite.append(jLabel13.getText() + "\n");
            buffWrite.append("Resposta: "+ resp6 + "\n");
            buffWrite.close();
            
            String query = "insert into quizz.UX (nome, email, data, p1, p2, p3, p4, p5, p6)"+"values(?, ?, ?, ?, ?, ?, ?, ?, ?)";
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizz", "root", "")) {
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, pnome+" "+unome);
                pst.setString(2, email);
                pst.setString(3, data);
            
                pst.setString(4, resp1);
                pst.setString(5, resp2);
                pst.setString(6, resp3);
                pst.setString(7, resp4);
                pst.setString(8, resp5);
                pst.setString(9, resp6);
                
                pst.executeUpdate();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Ux_frame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Prestreza_frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ux_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Pronto!");
        
        close();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton43ActionPerformed

    private void jRadioButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton48ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ux_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ux_frame(pnome, unome, email).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
